name: Build and Push to Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: leonardopoggiani/lmo-performance-evaluation
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set GOFLAGS environment variable
        run: export GOFLAGS="-mod-timeout=600"

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.21"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libbtrfs-dev libdevmapper-dev libgpgme-dev libseccomp-dev

      - name: Go Format
        run: gofmt -s -w .

      - name: Go mod tidy
        run: go mod tidy

      - name: Go Build
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags containers_image_openpgp -a -installsuffix cgo -o ./bin/performance-evaluation .

      - name: Go Compile Tests
        run: go test -exec /bin/true ./...

      - name: Go Test
        run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt ./... -timeout 20m

      - name: Go Benchmark
        run: go test -v -shuffle=on -run=- -bench=. -benchtime=1x ./...

      - name: Docker Build
        run: docker build -t docker.io/leonardopoggiani/performance-evaluation:ci .
